In [65]:
import numpy as np
import matplotlib.pyplot as plt

In [66]:
# Define link lengths for 6 DoF
a1, a2, a3, a4, a5, a6 = (0.0, 0.0, 0.07, 0.07, 0.07, 0.0)
a2

0.0

In [67]:
def dh_transformation_matrix(theta, a,d, alpha):
    cos_theta, cos_alpha = np.cos(theta), np.cos(alpha)
    sine_theta, sine_alpha = np.sin(theta), np.sin(alpha)

    matrix = np.array(
        [
            [cos_theta, -sine_theta*cos_alpha, sine_theta*sine_alpha, a*cos_theta],
            [sine_theta, cos_theta*cos_alpha, -cos_theta*sine_alpha, a*sine_theta],
            [0, sine_alpha, cos_alpha, d],
            [0, 0, 0, 1]
        ]
    )

    return matrix

In [68]:
def forward_kinematics(thetas):
    T1 = dh_transformation_matrix(thetas[0], a1, 0, 90)
    T2 = dh_transformation_matrix(thetas[1], a2, 0, 0)
    T3 = dh_transformation_matrix(thetas[2], a3, 0, 0)
    T4 = dh_transformation_matrix(thetas[3], a4, 0, 90)
    T5 = dh_transformation_matrix(thetas[4], a5, 0, 0)
    T6 = dh_transformation_matrix(thetas[5], a6, 0, -90)

    T_final = T1 @ T2 @ T3 @ T4 @ T5 @ T6
    
    return T_final

In [69]:
# !pip install ikpy

In [70]:
from ikpy.chain import Chain

my_chain = Chain.from_urdf_file("robot.urdf")

target_position = [0.1, 0.1, 0.2]

joint_angles = my_chain.inverse_kinematics(target_position)

print("Joint angles:", joint_angles)

print("End-effector pose:")
print(my_chain.forward_kinematics(joint_angles))


Joint angles: [ 0.          1.10714407  1.9913497  -0.7854249   1.57080495  0.
  0.        ]
End-effector pose:
[[-0.89442496 -0.15957421  0.41777993  0.0689919 ]
 [-0.00001101 -0.93416713 -0.35683578  0.06899191]
 [ 0.44721807 -0.31916743  0.83554064  0.13798379]
 [ 0.          0.          0.          1.        ]]


In [71]:
np.set_printoptions(suppress=True, precision=10)
fk_ikpy = my_chain.forward_kinematics(joint_angles)
thetas = list(joint_angles)
print(forward_kinematics(thetas))
print(fk_ikpy)

[[ 0.33020665 -0.89186055  0.30910892 -0.09413804]
 [-0.93494053 -0.26399954  0.23704523 -0.08991128]
 [-0.12980668 -0.36727237 -0.92101098  0.03972699]
 [ 0.          0.          0.          1.        ]]
[[-0.89442496 -0.15957421  0.41777993  0.0689919 ]
 [-0.00001101 -0.93416713 -0.35683578  0.06899191]
 [ 0.44721807 -0.31916743  0.83554064  0.13798379]
 [ 0.          0.          0.          1.        ]]


In [ ]:
x = fk_ipy[0]